# Generated by Django 4.1.2 on 2022-10-28 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_alter_familiares_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
