# Generated by Django 4.1.2 on 2022-10-28 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_familiares_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='edad',
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 11, 57, 52, 785952)),
        ),
    ]
