# Generated by Django 4.1.2 on 2022-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_remove_familiares_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
